# Generated by Django 2.2 on 2019-05-06 22:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('APILibraryApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookID', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('languages', models.CharField(max_length=200)),
                ('page_count', models.IntegerField()),
                ('publish_date', models.IntegerField()),
                ('publisher', models.CharField(max_length=200)),
                ('isbn', models.TextField()),
                ('ebook', models.BooleanField()),
                ('description', models.TextField()),
                ('thumbnail', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(related_name='books', to='APILibraryApp.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='BookItem',
        ),
        migrations.AddField(
            model_name='book',
            name='category_tags',
            field=models.ManyToManyField(related_name='books', to='APILibraryApp.Category'),
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ManyToManyField(related_name='books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='user_tags',
            field=models.ManyToManyField(related_name='books', to='APILibraryApp.UserTag'),
        ),
    ]
