# Generated by Django 2.2 on 2019-05-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APILibraryApp', '0002_auto_20190506_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.CharField(max_length=200),
        ),
    ]
