# Generated by Django 2.2 on 2019-05-06 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APILibraryApp', '0003_auto_20190506_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='user',
            new_name='users',
        ),
    ]
