# Generated by Django 2.2 on 2019-05-07 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APILibraryApp', '0004_auto_20190506_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
