# Generated by Django 2.2 on 2019-05-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APILibraryApp', '0005_auto_20190507_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
