# Generated by Django 2.2 on 2019-05-17 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('APILibraryApp', '0007_auto_20190509_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='users',
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField()),
                ('impressions', models.TextField()),
                ('impressions_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userbooks', to='APILibraryApp.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userbooks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
