# Generated by Django 2.2 on 2019-05-09 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0002_auto_20190509_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_name',
            new_name='username',
        ),
    ]
